import os
from dotenv import load_dotenv

# load_dotenv(r'env_\nid.env')
load_dotenv(r'env_\rpa.env')

## BASE PAGE
SCROLL_DOWN_PIXELS = os.getenv('SCROLL_DOWN_PIXELS')
MAX_WAIT = os.getenv('MAX_WAIT')

## MAIN PAGE: CIB LOGIN PAGE 
 
CIB_LOGIN_URL =os.getenv('CIB_LOGIN_URL')
USERNAME =os.getenv('USERNAME_XPATH')
PASSWORD = os.getenv('PASSWORD_XPATH')
CAPTCHA_BOX = os.getenv('CAPTCHA_BOX')
CAPTCHA_TEXT = os.getenv('CAPTCHA_TEXT')
LOGIN_BTN = os.getenv('LOGIN_BTN')

## 
SUBJECT_ROLE = os.getenv('SUBJECT_ROLE')
TYPE_OF_FINANCE = os.getenv('TYPE_OF_FINANCE')
NUMBER_OF_INSTALLMENT = os.getenv('NUMBER_OF_INSTALLMENT')
INSTALLMENT_AMOUNT = os.getenv('INSTALLMENT_AMOUNT')
TOTAL_FINANCE_AMOUNT = os.getenv('TOTAL_FINANCE_AMOUNT')
PERIODICITY_OF_PAYMMENT = os.getenv('PERIODICITY_OF_PAYMMENT')

TITLE = os.getenv('TITLE')
NAME = os.getenv('NAME')
FATHER_TITLE = os.getenv('FATHER_TITLE')
FATHER_NAME = os.getenv('FATHER_NAME')
MOTHER_TITLE = os.getenv('MOTHER_TITLE')
MOTHER_NAME = os.getenv('MOTHER_NAME')
SPOUSE_TITLE = os.getenv('SPOUSE_TITLE')
SPOUSE_NAME = os.getenv('SPOUSE_NAME')

NID = os.getenv('NID')
TIN = os.getenv('TIN')
DOB = os.getenv('DOB')
GENDER = os.getenv('GENDER')
DIST_OF_BIRTH = os.getenv('DIST_OF_BIRTH')

PERMANENT_ADDRESS_DISTRICT  = os.getenv('PERMANENT_ADDRESS_DISTRICT ')
PERMANENT_ADDRESS_STREET = os.getenv('PERMANENT_ADDRESS_STREET')
PERMANENT_POSTAL_CODE  = os.getenv('PERMANENT_POSTAL_CODE ')

PRESENT_ADDRESS_DISTRICT = os.getenv('PRESENT_ADDRESS_DISTRICT')
PRESENT_ADDRESS_STREET = os.getenv('PRESENT_ADDRESS_STREET')
PRESENT_POSTAL_CODE = os.getenv('PRESENT_POSTAL_CODE') 

ID_TYPE = os.getenv('ID_TYPE')
ID_NUMBER = os.getenv('ID_NUMBER')
ID_ISSUE_DATE = os.getenv('ID_ISSUE_DATE')
ID_ISSUE_COUNTRY = os.getenv('ID_ISSUE_COUNTRY')

SECTOR_TYPE = os.getenv('SECTOR_TYPE')
SECTOR_CODE = os.getenv('SECTOR_CODE')

TELEPHONE_NUMBER = os.getenv('TELEPHONE_NUMBER')

CONTRACT_HISTORY = os.getenv('CONTRACT_HISTORY') 

CONTRACT_PHASE = os.getenv('CONTRACT_PHASE')

INDIVIDUAL_NEW_INQUIRY = os.getenv('INDIVIDUAL_NEW_INQUIRY') 
