# from selenium.webdriver.common.by import By
# from src.main.utils.config.env_.rpa import CIB_LOGIN_URL, USERNAME, \
#     PASSWORD, CAPTCHA_TEXT, CAPTCHA_BOX, LOGIN_BTN, SUBJECT_ROLE, TYPE_OF_FINANCE, NUMBER_OF_INSTALLMENT, \
#     INSTALLMENT_AMOUNT, TOTAL_FINANCE_AMOUNT, TITLE, NAME, FATHER_TITLE, FATHER_NAME, MOTHER_TITLE, \
#     MOTHER_NAME, SPOUSE_TITLE, SPOUSE_NAME, NID, TIN, DOB, GENDER, DIST_OF_BIRTH, PERMANENT_ADDRESS_DISTRICT, \
#     PERMANENT_ADDRESS_STREET, PERMANENT_POSTAL_CODE, PRESENT_ADDRESS_DISTRICT, PRESENT_ADDRESS_STREET, \
#     PRESENT_POSTAL_CODE, ID_TYPE, ID_NUMBER, ID_ISSUE_DATE, ID_ISSUE_COUNTRY, SECTOR_TYPE, SECTOR_CODE, \
#     TELEPHONE_NUMBER, CONTRACT_HISTORY, CONTRACT_PHASE, INDIVIDUAL_NEW_INQUIRY, PERIODICITY_OF_PAYMMENT

# class CIBNewInquiryPageLocator:
#     URL = CIB_LOGIN_URL
    
#     USERNAME = (By.XPATH, USERNAME)
#     PASSWORD = (By.XPATH, PASSWORD)
#     CAPTCHA_TEXT =(By.XPATH, CAPTCHA_TEXT)
#     CAPTCHA_BOX = (By.XPATH, CAPTCHA_BOX)
#     LOGIN_BTN = (By.XPATH, LOGIN_BTN) 

#     SUBJECT_ROLE = (By.XPATH, SUBJECT_ROLE)
#     TYPE_OF_FINANCELOGIN_BTN = (By.XPATH, TYPE_OF_FINANCE)
#     NUMBER_OF_INSTALLMENT = (By.XPATH, NUMBER_OF_INSTALLMENT)
#     INSTALLMENT_AMOUNT = (By.XPATH, INSTALLMENT_AMOUNT)
#     TOTAL_FINANCE_AMOUNT = (By.XPATH, TOTAL_FINANCE_AMOUNT)
#     PERIODICITY_OF_PAYMMENT = (By.XPATH, PERIODICITY_OF_PAYMMENT)

#     TITLE = (By.XPATH, TITLE)
#     NAME = (By.XPATH, NAME)
#     FATHER_TITLE = (By.XPATH, FATHER_TITLE)
#     FATHER_NAME = (By.XPATH, FATHER_NAME)
#     MOTHER_TITLE = (By.XPATH, MOTHER_TITLE)
#     MOTHER_NAME = (By.XPATH, MOTHER_NAME)
#     SPOUSE_TITLE = (By.XPATH, SPOUSE_TITLE)
#     SPOUSE_NAME = (By.XPATH, SPOUSE_NAME) 

#     NID = (By.XPATH, NID)
#     TIN = (By.XPATH, TIN)
#     DOB = (By.XPATH, DOB)
#     GENDER = (By.XPATH, GENDER)
#     DIST_OF_BIRTH = (By.XPATH, DIST_OF_BIRTH)

#     PERMANENT_ADDRESS_DISTRICT = (By.XPATH, PERMANENT_ADDRESS_DISTRICT)
#     PERMANENT_ADDRESS_STREET = (By.XPATH, PERMANENT_ADDRESS_STREET)
#     PERMANENT_POSTAL_CODE = (By.XPATH, PERMANENT_POSTAL_CODE)

#     PRESENT_ADDRESS_DISTRICT = (By.XPATH, PRESENT_ADDRESS_DISTRICT)
#     PRESENT_ADDRESS_STREET = (By.XPATH, PRESENT_ADDRESS_STREET)
#     PRESENT_POSTAL_CODE = (By.XPATH, PRESENT_POSTAL_CODE) 

#     ID_TYPE = (By.XPATH, ID_TYPE)
#     ID_NUMBER = (By.XPATH, ID_NUMBER)
#     ID_ISSUE_DATE = (By.XPATH, ID_ISSUE_DATE)
#     ID_ISSUE_COUNTRY = (By.XPATH, ID_ISSUE_COUNTRY)

#     SECTOR_TYPE = (By.XPATH, SECTOR_TYPE)
#     SECTOR_CODE = (By.XPATH, SECTOR_CODE)
#     TELEPHONE_NUMBER = (By.XPATH, TELEPHONE_NUMBER)
#     CONTRACT_HISTORY = (By.XPATH, CONTRACT_HISTORY)
#     CONTRACT_PHASE = (By.XPATH, CONTRACT_PHASE)
#     INDIVIDUAL_NEW_INQUIRY = (By.XPATH, INDIVIDUAL_NEW_INQUIRY)
    